---
title: "Day 2"
description: |
  Advanced Research Skills & Professional Development

css: "style.css"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## SESSION 1: Reference Management & Literature Organization (50 minutes)


### Part A: Zotero for Research Management



**Literature Search Platforms**

🗂 [Scholar Google](https://scholar.google.com/)

🗂️ [Lens.org](https://www.lens.org/lens/search/scholar/structured)

🗂 [Connectedpapers](https://www.connectedpapers.com/)

**Set Up Zotero**

<details class="collapsible">
<summary>Download and Install Zotero (Recommended before the workshop)</summary>

- Go to [Zotero.org/download](https://www.zotero.org/download/)
- Download Zotero Desktop (Windows, macOS, or Linux).
- Install the software on your computer [Video Instructions](https://www.youtube.com/watch?v=JG7Uq_JFDzE).

</details>


<details class="collapsible">
<summary>Install the Zotero Connector (Recommended before the workshop)</summary>


- [Download the Zotero Connector](https://chrome.google.com/webstore/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc) for your browser (Chrome, Firefox, Edge, or Safari).

*This lets you save references directly from websites, databases, and Google Scholar.*

</details>



<details class="collapsible">
<summary>Create a Zotero Account (Recommended before the workshop)</summary>


- Go to [Zotero.org](https://www.zotero.org/user/register/)
- Sign up for a free account (needed for syncing your library across devices).

</details>



<details class="collapsible">
<summary> Sync Your Library (Recommended before the workshop)</summary>

- Open the Zotero desktop app.
- Go to Edit → Preferences → Sync.
- Enter your Zotero account details and enable syncing.

</details>



<details class="collapsible">
<summary> Sync Your Library (Recommended before the workshop)</summary>

- Open the Zotero desktop app.
- Go to Edit → Preferences → Sync.
- Enter your Zotero account details and enable syncing.

</details>


<details class="collapsible">
<summary> Sync Your Library (Recommended before the workshop)</summary>

- Open the Zotero desktop app.
- Go to Edit → Preferences → Sync.
- Enter your Zotero account details and enable syncing.

</details>


<details class="collapsible">
<summary> Sync Your Library (Recommended before the workshop)</summary>

- Open the Zotero desktop app.
- Go to Edit → Preferences → Sync.
- Enter your Zotero account details and enable syncing.

</details>


## SESSION 2: Data Collection and Analysis & AI-Enhanced Literature Review (70 minutes)

### Part A: Kobotoolbox for Data Collection


### Part B: MAXQDA for Qualitative Research Analysis


### Part C: AI-Enhanced Literature Review




[← Back: Day 1](https://jopscipworkshop.netlify.app/august25) | 
